### ISSUE TITLE
eks-pod-identity-agent session name for use with MSK

### ISSUE THREAD

**Issue by metropolis-ameer** [aws/eks-pod-identity-agent#29]
eks-pod-identity-agent needs the ability to set a static session name for the role in use rather than generating a random session name.  This creates an issue where the eks-pod-identity-agent refreshes the role credentials and causes a fatal error continuing to connect to MSK because it expects the same session name.

**Comment by Santiacmaestre** [comment]
We’ve hit the same problem: eks-pod-identity-agent rotates credentials and generates a new STS session name, which makes MSK reject re-auth with “Cannot change principals during re-authentication” because the principal effectively changes.

Until the agent supports a static session name, here’s a workaround that kept us stable in production-like tests (Java/Spring Boot):

### Workaround (validated for Java / Spring Boot)
Keep Pod Identity as the base provider, but have the app explicitly assume a dedicated IAM role for MSK with a fixed session name:
1. Create a dedicated IAM role for MSK access (produce/consume).
    - Move Kafka permissions to this role.
2. Trust policy: allow your Pod Identity role to sts:AssumeRole into this dedicated role.
3. App config (Java): set both a static awsRoleSessionName and the awsRoleArn in the MSK IAM client settings so every re-auth uses the same assumed role + session name.

### Example (YAML) for Spring Boot / Spring Cloud Stream (Kafka binder):
```yaml
spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
              sasl:
                # login.callback.handler.class: software.amazon.msk.auth.iam.IAMOAuthBearerLoginCallbackHandler
                mechanism: AWS_MSK_IAM
                client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
                jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::[account-id]:role/[role-name]" awsRoleSessionName="[static-session-name]"  awsStsRegion="[region-name]";
                security.protocol: SASL_SSL
```

### Why this helps
- Pod Identity will still refresh tokens and create random sessions for its own role, but your app always assumes the same dedicated role with a fixed session name when talking to MSK.
- From MSK’s perspective, the principal stays stable across re-auth cycles.

### Results
- We ran 8–10h soak tests on multiple Java services; no more “principal changed” auth failures after implementing the above.

### Notes / Caveats
- Keep the dedicated role least-privilege (only access to MSK Kafka, cluster, topics and groups you need)
- Ensure the trust relationship from Pod Identity → dedicated MSK role is correct.
- This is a workaround; the ideal fix is support in the agent for a static session name to avoid this extra assume-role hop.

<img width="1120" height="499" alt="Image" src="https://github.com/user-attachments/assets/ac7645a3-d9fc-40c9-afd2-ae73596d5492" />
