### ISSUE TITLE
Agent CrashLoopBackOff when metrics enabled via helm

### ISSUE THREAD

**Issue by antonbriganti-seek** [aws/eks-pod-identity-agent#40]
When we have enabled metrics via the helm chart, our pods are unable to start due to an "unknown flag" error relating to the --metrics-port argument. We can see that it's in the `server.go` file so we're not sure why the app is saying that it's an unknown flag

We're pulling image tag `0.1.17` so should be on the latest.

Is there any guidance on why we were getting this error?

### logs
```
Defaulted container "eks-pod-identity-agent" out of: eks-pod-identity-agent, eks-pod-identity-agent-init (init)
2025/01/21 06:24:26 Running command:
Command env: (log-file=, also-stdout=false, redirect-stderr=true)
Run from directory:
Executable path: /eks-pod-identity-agent
Args (comma-delimited): /eks-pod-identity-agent,server,--port,80,--cluster-name,EKS_CLUSTER_NAME,--probe-port,2703,--metrics-port,2705,-v,trace
2025/01/21 06:24:26 Now listening for interrupts
Error: unknown flag: --metrics-port
Usage:
  eks-pod-identity-agent server [flags]

Flags:
  -b, --bind-hosts stringArray                             Hosts to bind server to (default [169.254.170.23,[fd00:ec2::23]])
  -c, --cluster-name string                                Name of the EKS Cluster the agent will run on
      --endpoint string                                    Override for EKS auth endpoint
  -h, --help                                               help for server
      --max-cache-size int                                 Maximum amount of unique credentials to cache. Set 0 to disable caching. (default 2000)
      --max-credential-retention-before-renewal duration   Maximum amount of time that agent waits before renewing credentials. Set 0 to disable caching. (default 3h0m0s)
      --max-service-qps int                                Maximum amount of queries per second to EKS Auth (default 3)
  -p, --port uint16                                        Listening port of the proxy server (default 80)
      --probe-port uint16                                  Health and readiness listening port (default 2703)
      --rotate-credentials                                 Enable credentials rotation from shared credentials file

Global Flags:
  -v, --verbosity string   Logging verbosity can be one of: panic, error, info, trace (default "info")

2025/01/21 06:24:26 running command: exit status 1
```

### helm chart
default except for 
```
metrics:
  enabled: true
  port: 2705
  path: /metrics
  # extraLabels:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "2705"
  serviceMonitor:
    enabled: false
    extraLabels: {}
    interval: "15s"

image:
  containerRegistry: "602401143452.dkr.ecr.us-west-2.amazonaws.com"
  pullPolicy: Always
  region: us-west-2
  tag: 0.1.17
```

**Comment by msarfaty** [comment]
there is a later version I found in ECR, the image tag is `v0.1.20` (looks like they have started to prepend `v`)

**Comment by egachi** [comment]
Hello, with the new image version `eks-pod-identity-agent:v0.1.20` we can enable the metrics through helm chart as followed:

```
metrics:
  enabled: true
  port: 2705
  path: /metrics
  extraLabels:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2705"
```

But doing it by managed addon in AWS console, it is not picking this value in the configuration file and failing to install the addon. Is this feature still unsupported via the AWS console?
